import Image from "next/image";
import Header from "@/components/header";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Search from "@/components/search";
export default function Home() {
  return (
    <>
      <Head>
        <title>EtherScan search</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="mini-logo.png"/>
      </Head>
      <section className={styles.main}>
        <p>Next Js</p>
        {/* <Header />
        <Search/> */}
      </section>
    </>
  );
}
